### ISSUE TITLE
分类的训练数据格式问题

### ISSUE THREAD

**Issue by standing88** [hjq133/piccolo-embedding#1]
分类的训练数据有没有例子  没太看明白那几列都该放什么数据

**Comment by hjq133** [comment]
我们在data_example提供了所有的数据格式。
其中 'cls.dataset' 就是分类和聚类的数据集格式。
包含四列: 
text: 原始分类数据的文本
text_pos: 原始分类文本的正样本标签（原始文本的标签）
text_neg: 其他负样本标签（即原始分类任务的其他类别标签）
type: 'cls_contrast'
type是个标志位，标志这个数据是需要用cls_contrast loss来训练

**Comment by standing88** [comment]
> 我们在data_example提供了所有的数据格式。 其中 'cls.dataset' 就是分类和聚类的数据集格式。 包含四列: text: 原始分类数据的文本 text_pos: 原始分类文本的正样本标签（原始文本的标签） text_neg: 其他负样本标签（即原始分类任务的其他类别标签） type: 'cls_contrast' type是个标志位，标志这个数据是需要用cls_contrast loss来训练

哦哦 明白了明白了 多谢!
