### ISSUE TITLE
疑似显存泄露的问题

### ISSUE THREAD

**Issue by xiayouran** [hjq133/piccolo-embedding#10]
你好，我在训练的过程中发现显存在持续性增长（4卡，训练了十几个小时），batch-size为8，显存占用由最初的十几个GB直到out of memory，如果我设置batch-size为16，一会儿就出现out of memory。想请教下作者在训练过程中有出现过类似的问题吗，正常应该是显存会被重复利用吧🙏

**Comment by hjq133** [comment]
不是的，这种情况应该是你的输入样本长度不一致，看上去最开始的sample的样本比较短，所以显存占用比较低，后面sample的样本比较长，所以显存占用会有增长。建议你先自己构造一些特别长度样本，然后测试下最大batch size能开到多少，然后再开始训练。

**Comment by xiayouran** [comment]
感谢👌，我尝试下
