### ISSUE TITLE
关于数据构造的问题

### ISSUE THREAD

**Issue by gaohongkui** [hjq133/piccolo-embedding#12]
非常感谢你们的工作！
想请教一下，piccolo-v2 最突出的特点应该就是多任务学习，但当微调数据不足以支撑提及的三大种任务时，本模型的微调是否就退化为其中一个任务，这样对最终模型的影响如何呢（会大幅下降吗）？

另外这也引申出一个问题：
如果我只有一种标注数据，例如 STS (相关性等级0,1,2) 
事实上我可以将其按照某种规则将其转化为 Retrieval 数据，例如 text, pos(1 & 2), neg (0)
也相当于用同一份数据做三种任务，这样的做法您觉得是有效的还是有害的呢～

还请不吝赐教 🙏

**Comment by hjq133** [comment]
对于第一个问题，三种任务，最终其实就两种损失，一种是针对粗粒度标注数据（Retri、Cls）采用的infonce，一种是针对细粒度标注数据（STS，有score得分）的cosent。所以我们的核心观点是针对不同形式标注的数据采用不同的损失。模型在微调的时候不一定要集齐三种任务的数据，有多少用多少就行，本身性能不会受影响。

对于第二个问题，STS可以转换成Retri的格式采用infonce，但这就和我们的初衷相悖了，因为对于细粒度标注的数据，进行这样的转换无疑会造成信息丢失，比如你这里的例子中，原本标注为1和2的数据，转换后就没区别了。所以这种数据，只用ranking loss就好了，没必要转换。

**Comment by gaohongkui** [comment]
感谢回答，修正了我的一些理解。我之前认为本文提出的不同 Loss 是为了不同的语义任务而生，但看了您上面的解答，这个观点应该是有问题的。事实上，本文的不同 Loss 形式是为了不同数据标注格式而设计。
那是否可以推出这样的使用场景：
- 目标：优化 QA 检索（非对称 Retrieval 任务）
- 数据：标注了 QA 的相关性等级(0, 1, 2)
- 使用本文方法：
	- 只做 CoSent loss 任务，模型既能做好不同 Answer 的 rank，也能兼容 Answer 在 Retrieval 时的 recall

**Comment by hjq133** [comment]
我认为是ok的。虽然我之前没尝试过，但我感觉你这儿采用cosent应该会比infonce好的，你也可以做个实验对比一下这里用两个损失在性能上区别。

**Comment by gaohongkui** [comment]
好的，感谢你的解答
