### ISSUE TITLE
为何模型不使用transofmer的decoder结构而使用bert结构作为特征提取呢

### ISSUE THREAD

**Issue by daicoolb** [hjq133/piccolo-embedding#13]
为何模型不使用transofmer的decoder结构而使用bert结构作为特征提取呢

**Comment by hjq133** [comment]
BERT在这类传统任务上的表现依旧会比GPT架构的模型好一些。不过现在也有使用decoder-only架构的模型，LLM类的模型最近在MTEB榜单上也有较好的表现。
