### ISSUE TITLE
微调问题

### ISSUE THREAD

**Issue by lalalabreeze** [hjq133/piccolo-embedding#14]
嗨，您好，我想向您请教几个问题
1、我有一个140多万的多分类任务数据集，请问我如果只是用piccolo-embedding来做embedding，然后接我的下游网络，请问我是直接在模型训练过程中在该数据集上进行微调，还是说我先在我的数据集上微调好了在接我的下游网络进行训练
2、支持2次预训练吗
谢谢解答

**Comment by hjq133** [comment]
hello 感谢关注，这里第一点我有点没太看明白，下游网络指什么，是分类器的那个线性层吗？所以你的问题是：
1. 直接在140万分类任务上用cross entropy微调整个bert
2. 在backbone（除了最后那个线性层）上进行contrastive learning训练，然后再接上线性层进行分类训练
如果是这种比较的话，第一种通常更直接吧，第二种看上去有点没有必要。

第二点，是支持二次预训练的，这个repo只是提供了一种multi-task的训练方式，当然可以进行二次预训练。

**Comment by lalalabreeze** [comment]
谢谢解答，非常优秀的工作
