### ISSUE TITLE
NEG_NUM的消融实验

### ISSUE THREAD

**Issue by STHSF** [hjq133/piccolo-embedding#17]
技术报告中没有提到关于NEG_NUM的消融实验，可以分享一下NEG_NUM不同的取值对效果的影响不？

**Comment by hjq133** [comment]
hello，时间长有点忘了。我跑当时的结论是这些数据集上neg num增多没有太大的收益（当然有可能是我挖掘出的neg sample质量不好）。最后就设置了neg_num=1。

**Comment by STHSF** [comment]
多谢解答
