### ISSUE TITLE
这个模型用cls  用来做分类模型该如何使用呢

### ISSUE THREAD

**Issue by standing88** [hjq133/piccolo-embedding#4]
大佬 能不能提供一下分类模型的调用方法

**Comment by hjq133** [comment]
请问你是想直接做zero-shot，还是需要再训一个线性层做分类呢？
对于前者，直接比较label和text的相似度然后取最大值就ok
```python
# for s2s/s2p dataset, you can use piccolo as below
from sklearn.preprocessing import normalize
from sentence_transformers import SentenceTransformer
sentences = ["文本1"]
labels = ["标签1", "标签2", "标签3"...]
model = SentenceTransformer('your_model')
embeddings_1 = model.encode(sentences, normalize_embeddings=True)
embeddings_2 = model.encode(sentences, normalize_embeddings=True)
然后计算embeddings1和embeddings2的相似度，取argmax的标签就ok
```

如果是还要训一个线性层，可以参考MTEB里的classification evaluator那种方式:
https://github.com/embeddings-benchmark/mteb/blob/main/mteb/evaluation/evaluators/ClassificationEvaluator.py

**Comment by standing88** [comment]
> 请问你是想直接做zero-shot，还是需要再训一个线性层做分类呢？ 对于前者，直接比较label和text的相似度然后取最大值就ok
> 
> ```python
> # for s2s/s2p dataset, you can use piccolo as below
> from sklearn.preprocessing import normalize
> from sentence_transformers import SentenceTransformer
> sentences = ["文本1"]
> labels = ["标签1", "标签2", "标签3"...]
> model = SentenceTransformer('your_model')
> embeddings_1 = model.encode(sentences, normalize_embeddings=True)
> embeddings_2 = model.encode(sentences, normalize_embeddings=True)
> 然后计算embeddings1和embeddings2的相似度，取argmax的标签就ok
> ```
> 
> 如果是还要训一个线性层，可以参考MTEB里的classification evaluator那种方式: https://github.com/embeddings-benchmark/mteb/blob/main/mteb/evaluation/evaluators/ClassificationEvaluator.py

好的,感谢大佬指点
