### ISSUE TITLE
请教下扩展bert长度问题

### ISSUE THREAD

**Issue by NLPJCL** [hjq133/piccolo-embedding#6]
您好，很好的工作！请教一个问题。
1.看代码里，扩展bert长度是复制原来512的绝对位置编码的权重到要扩展的对应位置，请问下这块有尝试过不同的方法嘛？
比如苏剑林的层次分解位置编码，或者大于512的地方直接随机初始化呢？
https://github.com/hjq133/piccolo-embedding/blob/9dd1d66cd47981b462d76a6040507663e87ee143/piccolo/model.py#L176C1-L177C1

**Comment by hjq133** [comment]
抱歉才看到。我这里的代码似乎有问题，这里当时本意是想弄层次分解位置编码的，但是似乎代码版本传错了。不过这种迭代复制的方式去初始化效果也是不错的，但是这块并没有做太多消融实验，没有去比较和随机初始化的区别。
ps: 后面有时间我会再改动下代码。传一个层次分解的版本上来。

**Comment by NLPJCL** [comment]
好的，多谢！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月28日(周二) 晚上6:58
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [hjq133/piccolo-embedding] 请教下扩展bert长度问题 (Issue #6)




 
抱歉才看到。我这里的代码似乎有问题，这里当时本意是想弄层次分解位置编码的，但是似乎代码版本传错了。不过这种迭代复制的方式去初始化效果也是不错的，但是这块并没有做太多消融实验，没有去比较和随机初始化的区别。
 ps: 后面有时间我会再改动下代码。传一个层次分解的版本上来。
