### ISSUE TITLE
请教一下训练的问题

### ISSUE THREAD

**Issue by standing88** [hjq133/piccolo-embedding#7]
大佬我想请教一下训练的问题
比方说我训练cls分类模型   第一次微调用了10000条数据,下一次又有了100条新样本 ,我是将这100条添加进初始的10000条中重新训练好呢,还是直接用第一次训练出的模型微调这100条更好一些呢

**Comment by hjq133** [comment]
这个是经典的continual learning问题，一般来说直接用第一次训练出的模型继续微调的话，会出现catastrophic forgetting（灾难性遗忘现象）。所以最好的方式是将100条加到10000条里重新训。但有时候为了节省成本，我们也会在第一次训练出的模型上进行微调，但会通过一些技术手段防止其遗忘，比如最经典的ewc正则化、或者data replay策略（从10000条里sample一个子集，混合到100条里进行续训）

**Comment by standing88** [comment]
> 这个是经典的continual learning问题，一般来说直接用第一次训练出的模型继续微调的话，会出现catastrophic forgetting（灾难性遗忘现象）。所以最好的方式是将100条加到10000条里重新训。但有时候为了节省成本，我们也会在第一次训练出的模型上进行微调，但会通过一些技术手段防止其遗忘，比如最经典的ewc正则化、或者data replay策略（从10000条里sample一个子集，混合到100条里进行续训）

懂了懂了 感谢大佬不吝赐教受益匪浅

**Comment by hjq133** [comment]
hh没事的
