### ISSUE TITLE
The parameter 388 has already been reduced

### ISSUE THREAD

**Issue by ToddBear** [hjq133/piccolo-embedding#8]
[default0]:AssertionError: The parameter 388 has already been reduced.             Gradient computed twice for this partition.             Multiple gradient reduction is currently not supported

How can i solved this problem?

**Comment by hjq133** [comment]
use Deepspeed zero2?
please use zero1,  I remember the bi-encoder is incompatible with zero2

**Comment by ToddBear** [comment]
I uses zeor1. Disable gradient_checkpoint solved the problem.
