### ISSUE TITLE
请教一下，我有一份40w的摘要数据，想以piccolo2为预训练模型做微调，打算以构建正样本对的方式去训练，该对训练脚本做哪些更改呢

### ISSUE THREAD

**Issue by DeerEyre** [hjq133/piccolo-embedding#9]
请教一下，我有一份40w的摘要数据，想以piccolo2为预训练模型做微调，打算以构建正样本对的方式去训练，该对训练脚本做哪些更改呢

**Comment by hjq133** [comment]
你的pair对是 {摘要：内容} 吗？那其实可以采用 ‘Retri’ 的那种构建方式，把摘要作为text，把内容作为text_pos，text_neg可以置空。训练脚本不用更改的，只需要构建下数据集就好了。

**Comment by DeerEyre** [comment]
十分感谢您的回答，还有个问题，部分摘要数据没有对应的内容，text_pos可以置空吗。目前piccolo2模型是不是还暂未开源，无法在其基础上进行微调？

**Comment by hjq133** [comment]
1. text_pos不能置空的，但如果text_neg质量高的话，可以考虑把text和text_pos设置成一模一样，来增加text_neg的利用率。否则如果一个样本的text_pos和text_neg都没有的话，最好就丢掉该样本。
2. 是的，piccolo2只提供了api，不过cmteb榜单上前几名有不少模型采用了我们的训练方式，你也可以考虑使用他们的模型。
